/**
 * Dolch 95 nouns plus common kid-vocabulary words, in the compact
 * lexicon notation described in ./notation.ts.
 */
export const WORDS_NOUNS: Record<string, string> = {
  // --- Dolch nouns ---
  apple: 'a.p-p.l.e:X',
  baby: 'b.a/A-b.y/E',
  back: 'b.a.ck:D',
  ball: 'b.a/aw.ll',
  bear: 'b.ear/air',
  bed: 'b.e.d',
  bell: 'b.e.ll',
  bird: 'b.ir/er.d',
  birthday: 'b.ir/er.th:D-d.ay/A',
  boat: 'b.oa/O.t',
  box: 'b.o.x',
  boy: 'b.oy/oy',
  bread: 'b.r.ea/e:H.d',
  brother: 'b.r.o/u:H-th:D.er/er',
  cake: 'c.a/A.k.e:X',
  car: 'c.ar/ar',
  cat: 'c.a.t',
  chair: 'ch:D.air/air',
  chicken: 'ch:D.i.ck:D-e.n',
  children: 'ch:D.i.l-d.r.e.n',
  christmas: 'ch:DH=k.r.i.s.t:X-m.a/uh.s',
  coat: 'c.oa/O.t',
  corn: 'c.or/or.n',
  cow: 'c.ow/ow',
  day: 'd.ay/A',
  dog: 'd.o.g',
  doll: 'd.o.ll',
  door: 'd.oor/or',
  duck: 'd.u.ck:D',
  egg: 'e.gg',
  eye: 'eye/I:H',
  farm: 'f.ar/ar.m',
  farmer: 'f.ar/ar.m-er/er',
  father: 'f.a/o-th:D.er/er',
  feet: 'f.ee/E.t',
  fire: 'f.i/I.r.e:X',
  fish: 'f.i.sh:D',
  floor: 'f.l.oor/or',
  flower: 'f.l.ow/ow-er/er',
  game: 'g.a/A.m.e:X',
  garden: 'g.ar/ar-d.e.n',
  girl: 'g.ir/er.l',
  goodbye: 'g.oo/uu.d-b.y/I.e:X',
  grass: 'g.r.a.ss',
  ground: 'g.r.ou/ow.n.d',
  hand: 'h.a.n.d',
  head: 'h.ea/e:H.d',
  hill: 'h.i.ll',
  home: 'h.o/O.m.e:X',
  horse: 'h.or/or.s.e:X',
  house: 'h.ou/ow.s.e:X',
  kitty: 'k.i.t-t.y/E',
  leg: 'l.e.g',
  letter: 'l.e.t-t.er/er',
  man: 'm.a.n',
  men: 'm.e.n',
  milk: 'm.i.l.k',
  money: 'm.o/u:H-n.ey/E',
  morning: 'm.or/or.n-i.ng:D',
  mother: 'm.o/u:H-th:D.er/er',
  name: 'n.a/A.m.e:X',
  nest: 'n.e.s.t',
  night: 'n.igh/I.t',
  paper: 'p.a/A-p.er/er',
  party: 'p.ar/ar-t.y/E',
  picture: 'p.i.c-t.ure/er',
  pig: 'p.i.g',
  rabbit: 'r.a.b-b.i.t',
  rain: 'r.ai/A.n',
  ring: 'r.i.ng:D',
  robin: 'r.o.b-i.n',
  santa: 's.a.n-t.a/uh',
  school: 's.ch:DH=k.oo/oo.l',
  seed: 's.ee/E.d',
  sheep: 'sh:D.ee/E.p',
  shoe: 'sh:D.oe/oo:H',
  sister: 's.i.s-t.er/er',
  snow: 's.n.ow/O',
  song: 's.o.ng:D',
  squirrel: 's.qu:D.ir/er-r.e.l',
  stick: 's.t.i.ck:D',
  street: 's.t.r.ee/E.t',
  sun: 's.u.n',
  table: 't.a/A-b.l.e:X',
  thing: 'th:D.i.ng:D',
  time: 't.i/I.m.e:X',
  top: 't.o.p',
  toy: 't.oy/oy',
  tree: 't.r.ee/E',
  watch: 'w.a/o.tch:D',
  water: 'w.a/aw:H-t.er/er',
  way: 'w.ay/A',
  wind: 'w.i.n.d',
  window: 'w.i.n-d.ow/O',
  wood: 'w.oo/uu.d',

  // --- family ---
  mommy: 'm.o.m-m.y/E',
  daddy: 'd.a.d-d.y/E',
  mom: 'm.o.m',
  dad: 'd.a.d',
  grandma: 'g.r.a.n.d-m.a/uh',
  grandpa: 'g.r.a.n.d-p.a/uh',
  mama: 'm.a/o-m.a/uh',
  papa: 'p.a/o-p.a/uh',
  friend: 'f.r.ie/e:H.n.d',

  // --- animals ---
  puppy: 'p.u.p-p.y/E',
  kitten: 'k.i.t-t.e.n',
  dinosaur: 'd.i/I-n.o/uh-s.au/aw.r',
  bunny: 'b.u.n-n.y/E',
  lion: 'l.i/I-o.n',
  tiger: 't.i/I-g.er/er',
  monkey: 'm.o/u:H.n-k.ey/E',
  elephant: 'e.l-e/uh-ph:D.a.n.t',
  frog: 'f.r.o.g',
  snake: 's.n.a/A.k.e:X',
  mouse: 'm.ou/ow.s.e:X',
  shark: 'sh:D.ar/ar.k',
  whale: 'wh:D.a/A.l.e:X',
  bug: 'b.u.g',
  bee: 'b.ee/E',
  owl: 'ow/ow.l',
  zebra: 'z.e/E-b.r.a/uh',
  giraffe: 'g:C.i/uh-r.a.ff.e:X',
  penguin: 'p.e.n-g.u.i.n',
  turtle: 't.ur/er-t.l.e:X',
  spider: 's.p.i/I-d.er/er',

  // --- things ---
  truck: 't.r.u.ck:D',
  train: 't.r.ai/A.n',
  bike: 'b.i/I.k.e:X',
  book: 'b.oo/uu.k',
  castle: 'c.a.s-t:X.l.e:X',
  robot: 'r.o/O-b.o.t',
  rocket: 'r.o.ck:D-e.t',
  dragon: 'd.r.a.g-o/uh.n',
  princess: 'p.r.i.n-c:C.e.ss',
  prince: 'p.r.i.n.c:C.e:X',
  pirate: 'p.i/I-r.a/uh.t.e:X',
  cookie: 'c.oo/uu-k.ie/E',
  pizza: 'p.i/E:H.zz:H=ts.a/uh',
  banana: 'b.a/uh-n.a.n-a/uh',
  cup: 'c.u.p',
  hat: 'h.a.t',
  block: 'b.l.o.ck:D',
  boot: 'b.oo/oo.t',
  bath: 'b.a.th:D',
  bus: 'b.u.s',
  plane: 'p.l.a/A.n.e:X',
  moon: 'm.oo/oo.n',
  star: 's.t.ar/ar',
  cloud: 'c.l.ou/ow.d',
  candy: 'c.a.n-d.y/E',
  juice: 'j.ui/oo:H.c:C.e:X',
  park: 'p.ar/ar.k',
  beach: 'b.ea/E.ch:D',
  bubble: 'b.u.b-b.l.e:X',
  sock: 's.o.ck:D',

  // --- days ---
  sunday: 's.u.n-d.ay/A',
  monday: 'm.o/u:H.n-d.ay/A',
  tuesday: 't.ue/oo.s-d.ay/A',
  wednesday: 'w.e.d:X-n.e.s:X-d.ay/A',
  thursday: 'th:D.ur/er.s-d.ay/A',
  friday: 'f.r.i/I-d.ay/A',
  saturday: 's.a.t-ur/er-d.ay/A',

  // --- colors ---
  red: 'r.e.d',
  blue: 'b.l.ue/oo',
  green: 'g.r.ee/E.n',
  yellow: 'y.e.l-l.ow/O',
  orange: 'or/or-a.n.g:C.e:X',
  purple: 'p.ur/er-p.l.e:X',
  pink: 'p.i.n.k',
  black: 'b.l.a.ck:D',
  white: 'wh:D.i/I.t.e:X',
  brown: 'b.r.ow/ow.n',

  // --- numbers ---
  one: 'o/u:H=wu.n.e:X',
  two: 't.w:X.o/oo:H',
  three: 'th:D.r.ee/E',
  four: 'f.our/or:H',
  five: 'f.i/I.v.e:X',
  six: 's.i.x',
  seven: 's.e.v-e.n',
  eight: 'eigh/A:H.t',
  nine: 'n.i/I.n.e:X',
  ten: 't.e.n',

  // --- sound / fun words ---
  zoom: 'z.oo/oo.m',
  boom: 'b.oo/oo.m',
  splash: 's.p.l.a.sh:D',
  yay: 'y.ay/A',
  wow: 'w.ow/ow',
  bang: 'b.a.ng:D',
  pop: 'p.o.p',
  crash: 'c.r.a.sh:D',
  wiggle: 'w.i.g-g.l.e:X',
  giggle: 'g.i.g-g.l.e:X',
  jump: 'j.u.m.p',
  hug: 'h.u.g',
  kiss: 'k.i.ss',
};
